export const CREATE_GAME = "CREATE_GAME";
export const CREATE_CARDLIST = "CREATE_CARDLIST";
export const TOGGLE_CARD = ' TOGGLE_CARD';
export const UPDATE_CARDS = "UPDATE_CARDS";
export const UPDATE_SELECTED_CARDS = "UPDATE_SELECTED_CARDS";
export const CLEAR_SELECTED_CARDS = "CLEAR_SELECTED_CARDS";
