export const CREATE_GAME = "CREATE_GAME";
export const CREATE_CARDLIST = "CREATE_CARDLIST";
export const TOGGLE_CARD = ' TOGGLE_CARD';
export const UPDATE_CARD = "UPDATE_CARD";
export const UPDATE_SELECTED_CARD = "UPDATE_SELECTED_CARD";
export const CLEAR_SELECTED_CARD = "CLEAR_SELECTED_CARD";
